apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictactoe-backend
  namespace: tictactoe-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-backend
  template:
    metadata:
      labels:
        app: game-backend
    spec:
      containers:
      - name: backend-container
        image: rkdocker1800/tictac:be
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: game-config
              key: REDIS_HOST
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: game-secret
              key: REDIS_PASSWORD
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: tictactoe-game
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: game-backend

